/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Properties of the validation model.
 *
 */
class ValidationModel {
  /**
   * Create a ValidationModel.
   * @member {string} repoUrl The repo url from where to construct the swagger
   * model.
   * @member {string} branch The branch of the repo from where to construct the
   * swagger model.
   * @member {string} resourceProvider The resource provider for whom to
   * construct the swagger model.
   * @member {string} apiVersion The api version of the resource provider to
   * construct the swagger model.
   * @member {number} duration The duration in seconds for which to run
   * validations against the model. The results of the validation will be
   * available only after this duration has passed.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ValidationModel
   *
   * @returns {object} metadata of ValidationModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ValidationModel',
      type: {
        name: 'Composite',
        className: 'ValidationModel',
        modelProperties: {
          repoUrl: {
            required: true,
            serializedName: 'repoUrl',
            constraints: {
              MinLength: 1
            },
            type: {
              name: 'String'
            }
          },
          branch: {
            required: true,
            serializedName: 'branch',
            constraints: {
              MinLength: 1
            },
            type: {
              name: 'String'
            }
          },
          resourceProvider: {
            required: true,
            serializedName: 'resourceProvider',
            constraints: {
              MinLength: 1
            },
            type: {
              name: 'String'
            }
          },
          apiVersion: {
            required: true,
            serializedName: 'apiVersion',
            constraints: {
              MinLength: 1
            },
            type: {
              name: 'String'
            }
          },
          duration: {
            required: true,
            serializedName: 'duration',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = ValidationModel;
