/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Response to a Create Validation Model request.
 *
 */
class ValidationModelCreateResponse {
  /**
   * Create a ValidationModelCreateResponse.
   * @member {string} [validationId] The id of the validation model created.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ValidationModelCreateResponse
   *
   * @returns {object} metadata of ValidationModelCreateResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ValidationModelCreateResponse',
      type: {
        name: 'Composite',
        className: 'ValidationModelCreateResponse',
        modelProperties: {
          validationId: {
            required: false,
            readOnly: true,
            serializedName: 'validationId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ValidationModelCreateResponse;
